package frc.robot.utils;

public enum AutonomousPath
{
    NOTHING,
    HARDCODED_SHOOT_DRIVE_BACK_AND_SHOOT,
    HARDCODED_SHOOT_DRIVE_BACK_AND_SHOOT_LOW,
    PATH_PLANNER_DRIVE_BACKWARDS,
    PATH_PLANNER_SHOOT_AND_DRIVE_BACKWARDS,
    PATH_PLANNER_SHOOT_INTAKE_TWO_BALLS,
    MAIN_NO_TERMINAL,
    MAIN_WITH_TERMINAL;
}
